# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: kessel/inventory/v1/health.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import kessel.inventory.v1.health_pb2 as kessel_dot_inventory_dot_v1_dot_health__pb2


class KesselInventoryHealthService(Protocol):
    async def get_livez(self, request: kessel_dot_inventory_dot_v1_dot_health__pb2.GetLivezRequest, ctx: RequestContext) -> kessel_dot_inventory_dot_v1_dot_health__pb2.GetLivezResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_readyz(self, request: kessel_dot_inventory_dot_v1_dot_health__pb2.GetReadyzRequest, ctx: RequestContext) -> kessel_dot_inventory_dot_v1_dot_health__pb2.GetReadyzResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class KesselInventoryHealthServiceASGIApplication(ConnectASGIApplication[KesselInventoryHealthService]):
    def __init__(self, service: KesselInventoryHealthService | AsyncGenerator[KesselInventoryHealthService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/kessel.inventory.v1.KesselInventoryHealthService/GetLivez": Endpoint.unary(
                    method=MethodInfo(
                        name="GetLivez",
                        service_name="kessel.inventory.v1.KesselInventoryHealthService",
                        input=kessel_dot_inventory_dot_v1_dot_health__pb2.GetLivezRequest,
                        output=kessel_dot_inventory_dot_v1_dot_health__pb2.GetLivezResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_livez,
                ),
                "/kessel.inventory.v1.KesselInventoryHealthService/GetReadyz": Endpoint.unary(
                    method=MethodInfo(
                        name="GetReadyz",
                        service_name="kessel.inventory.v1.KesselInventoryHealthService",
                        input=kessel_dot_inventory_dot_v1_dot_health__pb2.GetReadyzRequest,
                        output=kessel_dot_inventory_dot_v1_dot_health__pb2.GetReadyzResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_readyz,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kessel.inventory.v1.KesselInventoryHealthService"


class KesselInventoryHealthServiceClient(ConnectClient):
    async def get_livez(
        self,
        request: kessel_dot_inventory_dot_v1_dot_health__pb2.GetLivezRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kessel_dot_inventory_dot_v1_dot_health__pb2.GetLivezResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetLivez",
                service_name="kessel.inventory.v1.KesselInventoryHealthService",
                input=kessel_dot_inventory_dot_v1_dot_health__pb2.GetLivezRequest,
                output=kessel_dot_inventory_dot_v1_dot_health__pb2.GetLivezResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_readyz(
        self,
        request: kessel_dot_inventory_dot_v1_dot_health__pb2.GetReadyzRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kessel_dot_inventory_dot_v1_dot_health__pb2.GetReadyzResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetReadyz",
                service_name="kessel.inventory.v1.KesselInventoryHealthService",
                input=kessel_dot_inventory_dot_v1_dot_health__pb2.GetReadyzRequest,
                output=kessel_dot_inventory_dot_v1_dot_health__pb2.GetReadyzResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class KesselInventoryHealthServiceSync(Protocol):
    def get_livez(self, request: kessel_dot_inventory_dot_v1_dot_health__pb2.GetLivezRequest, ctx: RequestContext) -> kessel_dot_inventory_dot_v1_dot_health__pb2.GetLivezResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_readyz(self, request: kessel_dot_inventory_dot_v1_dot_health__pb2.GetReadyzRequest, ctx: RequestContext) -> kessel_dot_inventory_dot_v1_dot_health__pb2.GetReadyzResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class KesselInventoryHealthServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: KesselInventoryHealthServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            endpoints={
                "/kessel.inventory.v1.KesselInventoryHealthService/GetLivez": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetLivez",
                        service_name="kessel.inventory.v1.KesselInventoryHealthService",
                        input=kessel_dot_inventory_dot_v1_dot_health__pb2.GetLivezRequest,
                        output=kessel_dot_inventory_dot_v1_dot_health__pb2.GetLivezResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_livez,
                ),
                "/kessel.inventory.v1.KesselInventoryHealthService/GetReadyz": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetReadyz",
                        service_name="kessel.inventory.v1.KesselInventoryHealthService",
                        input=kessel_dot_inventory_dot_v1_dot_health__pb2.GetReadyzRequest,
                        output=kessel_dot_inventory_dot_v1_dot_health__pb2.GetReadyzResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_readyz,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kessel.inventory.v1.KesselInventoryHealthService"


class KesselInventoryHealthServiceClientSync(ConnectClientSync):
    def get_livez(
        self,
        request: kessel_dot_inventory_dot_v1_dot_health__pb2.GetLivezRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kessel_dot_inventory_dot_v1_dot_health__pb2.GetLivezResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetLivez",
                service_name="kessel.inventory.v1.KesselInventoryHealthService",
                input=kessel_dot_inventory_dot_v1_dot_health__pb2.GetLivezRequest,
                output=kessel_dot_inventory_dot_v1_dot_health__pb2.GetLivezResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_readyz(
        self,
        request: kessel_dot_inventory_dot_v1_dot_health__pb2.GetReadyzRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kessel_dot_inventory_dot_v1_dot_health__pb2.GetReadyzResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetReadyz",
                service_name="kessel.inventory.v1.KesselInventoryHealthService",
                input=kessel_dot_inventory_dot_v1_dot_health__pb2.GetReadyzRequest,
                output=kessel_dot_inventory_dot_v1_dot_health__pb2.GetReadyzResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
