# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kessel/inventory/v1beta2/check_bulk_response.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kessel/inventory/v1beta2/check_bulk_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kessel.inventory.v1beta2 import check_bulk_request_pb2 as kessel_dot_inventory_dot_v1beta2_dot_check__bulk__request__pb2
from kessel.inventory.v1beta2 import consistency_token_pb2 as kessel_dot_inventory_dot_v1beta2_dot_consistency__token__pb2
from kessel.inventory.v1beta2 import allowed_pb2 as kessel_dot_inventory_dot_v1beta2_dot_allowed__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from google.rpc import status_pb2 as google_dot_rpc_dot_status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2kessel/inventory/v1beta2/check_bulk_response.proto\x12\x18kessel.inventory.v1beta2\x1a\x31kessel/inventory/v1beta2/check_bulk_request.proto\x1a\x30kessel/inventory/v1beta2/consistency_token.proto\x1a&kessel/inventory/v1beta2/allowed.proto\x1a\x1b\x62uf/validate/validate.proto\x1a\x17google/rpc/status.proto\"T\n\x15\x43heckBulkResponseItem\x12;\n\x07\x61llowed\x18\x01 \x01(\x0e\x32!.kessel.inventory.v1beta2.AllowedR\x07\x61llowed\"\xe0\x01\n\x15\x43heckBulkResponsePair\x12H\n\x07request\x18\x01 \x01(\x0b\x32..kessel.inventory.v1beta2.CheckBulkRequestItemR\x07request\x12\x45\n\x04item\x18\x02 \x01(\x0b\x32/.kessel.inventory.v1beta2.CheckBulkResponseItemH\x00R\x04item\x12*\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x12.google.rpc.StatusH\x00R\x05\x65rrorB\n\n\x08response\"\xbd\x01\n\x11\x43heckBulkResponse\x12O\n\x05pairs\x18\x01 \x03(\x0b\x32/.kessel.inventory.v1beta2.CheckBulkResponsePairB\x08\xbaH\x05\x92\x01\x02\x08\x01R\x05pairs\x12W\n\x11\x63onsistency_token\x18\x02 \x01(\x0b\x32*.kessel.inventory.v1beta2.ConsistencyTokenR\x10\x63onsistencyTokenBr\n(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kessel.inventory.v1beta2.check_bulk_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(org.project_kessel.api.inventory.v1beta2P\001ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2'
  _globals['_CHECKBULKRESPONSE'].fields_by_name['pairs']._loaded_options = None
  _globals['_CHECKBULKRESPONSE'].fields_by_name['pairs']._serialized_options = b'\272H\005\222\001\002\010\001'
  _globals['_CHECKBULKRESPONSEITEM']._serialized_start=275
  _globals['_CHECKBULKRESPONSEITEM']._serialized_end=359
  _globals['_CHECKBULKRESPONSEPAIR']._serialized_start=362
  _globals['_CHECKBULKRESPONSEPAIR']._serialized_end=586
  _globals['_CHECKBULKRESPONSE']._serialized_start=589
  _globals['_CHECKBULKRESPONSE']._serialized_end=778
# @@protoc_insertion_point(module_scope)
