# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: kessel/inventory/v1beta2/inventory_service.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import kessel.inventory.v1beta2.check_bulk_request_pb2 as kessel_dot_inventory_dot_v1beta2_dot_check__bulk__request__pb2
import kessel.inventory.v1beta2.check_bulk_response_pb2 as kessel_dot_inventory_dot_v1beta2_dot_check__bulk__response__pb2
import kessel.inventory.v1beta2.check_for_update_bulk_request_pb2 as kessel_dot_inventory_dot_v1beta2_dot_check__for__update__bulk__request__pb2
import kessel.inventory.v1beta2.check_for_update_bulk_response_pb2 as kessel_dot_inventory_dot_v1beta2_dot_check__for__update__bulk__response__pb2
import kessel.inventory.v1beta2.check_for_update_request_pb2 as kessel_dot_inventory_dot_v1beta2_dot_check__for__update__request__pb2
import kessel.inventory.v1beta2.check_for_update_response_pb2 as kessel_dot_inventory_dot_v1beta2_dot_check__for__update__response__pb2
import kessel.inventory.v1beta2.check_request_pb2 as kessel_dot_inventory_dot_v1beta2_dot_check__request__pb2
import kessel.inventory.v1beta2.check_response_pb2 as kessel_dot_inventory_dot_v1beta2_dot_check__response__pb2
import kessel.inventory.v1beta2.check_self_bulk_request_pb2 as kessel_dot_inventory_dot_v1beta2_dot_check__self__bulk__request__pb2
import kessel.inventory.v1beta2.check_self_bulk_response_pb2 as kessel_dot_inventory_dot_v1beta2_dot_check__self__bulk__response__pb2
import kessel.inventory.v1beta2.check_self_request_pb2 as kessel_dot_inventory_dot_v1beta2_dot_check__self__request__pb2
import kessel.inventory.v1beta2.check_self_response_pb2 as kessel_dot_inventory_dot_v1beta2_dot_check__self__response__pb2
import kessel.inventory.v1beta2.delete_resource_request_pb2 as kessel_dot_inventory_dot_v1beta2_dot_delete__resource__request__pb2
import kessel.inventory.v1beta2.delete_resource_response_pb2 as kessel_dot_inventory_dot_v1beta2_dot_delete__resource__response__pb2
import kessel.inventory.v1beta2.report_resource_request_pb2 as kessel_dot_inventory_dot_v1beta2_dot_report__resource__request__pb2
import kessel.inventory.v1beta2.report_resource_response_pb2 as kessel_dot_inventory_dot_v1beta2_dot_report__resource__response__pb2
import kessel.inventory.v1beta2.streamed_list_objects_request_pb2 as kessel_dot_inventory_dot_v1beta2_dot_streamed__list__objects__request__pb2
import kessel.inventory.v1beta2.streamed_list_objects_response_pb2 as kessel_dot_inventory_dot_v1beta2_dot_streamed__list__objects__response__pb2
import kessel.inventory.v1beta2.streamed_list_subjects_request_pb2 as kessel_dot_inventory_dot_v1beta2_dot_streamed__list__subjects__request__pb2
import kessel.inventory.v1beta2.streamed_list_subjects_response_pb2 as kessel_dot_inventory_dot_v1beta2_dot_streamed__list__subjects__response__pb2


class KesselInventoryService(Protocol):
    async def check(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__request__pb2.CheckRequest,
        ctx: RequestContext,
    ) -> kessel_dot_inventory_dot_v1beta2_dot_check__response__pb2.CheckResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def check_self(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__self__request__pb2.CheckSelfRequest,
        ctx: RequestContext,
    ) -> kessel_dot_inventory_dot_v1beta2_dot_check__self__response__pb2.CheckSelfResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def check_for_update(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__for__update__request__pb2.CheckForUpdateRequest,
        ctx: RequestContext,
    ) -> (
        kessel_dot_inventory_dot_v1beta2_dot_check__for__update__response__pb2.CheckForUpdateResponse
    ):
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def check_for_update_bulk(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__for__update__bulk__request__pb2.CheckForUpdateBulkRequest,
        ctx: RequestContext,
    ) -> (
        kessel_dot_inventory_dot_v1beta2_dot_check__for__update__bulk__response__pb2.CheckForUpdateBulkResponse
    ):
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def check_bulk(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__bulk__request__pb2.CheckBulkRequest,
        ctx: RequestContext,
    ) -> kessel_dot_inventory_dot_v1beta2_dot_check__bulk__response__pb2.CheckBulkResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def check_self_bulk(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__self__bulk__request__pb2.CheckSelfBulkRequest,
        ctx: RequestContext,
    ) -> (
        kessel_dot_inventory_dot_v1beta2_dot_check__self__bulk__response__pb2.CheckSelfBulkResponse
    ):
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def report_resource(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_report__resource__request__pb2.ReportResourceRequest,
        ctx: RequestContext,
    ) -> (
        kessel_dot_inventory_dot_v1beta2_dot_report__resource__response__pb2.ReportResourceResponse
    ):
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_resource(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_delete__resource__request__pb2.DeleteResourceRequest,
        ctx: RequestContext,
    ) -> (
        kessel_dot_inventory_dot_v1beta2_dot_delete__resource__response__pb2.DeleteResourceResponse
    ):
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def streamed_list_objects(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_streamed__list__objects__request__pb2.StreamedListObjectsRequest,
        ctx: RequestContext,
    ) -> AsyncIterator[
        kessel_dot_inventory_dot_v1beta2_dot_streamed__list__objects__response__pb2.StreamedListObjectsResponse
    ]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def streamed_list_subjects(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_streamed__list__subjects__request__pb2.StreamedListSubjectsRequest,
        ctx: RequestContext,
    ) -> AsyncIterator[
        kessel_dot_inventory_dot_v1beta2_dot_streamed__list__subjects__response__pb2.StreamedListSubjectsResponse
    ]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class KesselInventoryServiceASGIApplication(ConnectASGIApplication[KesselInventoryService]):
    def __init__(
        self,
        service: KesselInventoryService | AsyncGenerator[KesselInventoryService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/kessel.inventory.v1beta2.KesselInventoryService/Check": Endpoint.unary(
                    method=MethodInfo(
                        name="Check",
                        service_name="kessel.inventory.v1beta2.KesselInventoryService",
                        input=kessel_dot_inventory_dot_v1beta2_dot_check__request__pb2.CheckRequest,
                        output=kessel_dot_inventory_dot_v1beta2_dot_check__response__pb2.CheckResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.check,
                ),
                "/kessel.inventory.v1beta2.KesselInventoryService/CheckSelf": Endpoint.unary(
                    method=MethodInfo(
                        name="CheckSelf",
                        service_name="kessel.inventory.v1beta2.KesselInventoryService",
                        input=kessel_dot_inventory_dot_v1beta2_dot_check__self__request__pb2.CheckSelfRequest,
                        output=kessel_dot_inventory_dot_v1beta2_dot_check__self__response__pb2.CheckSelfResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.check_self,
                ),
                "/kessel.inventory.v1beta2.KesselInventoryService/CheckForUpdate": Endpoint.unary(
                    method=MethodInfo(
                        name="CheckForUpdate",
                        service_name="kessel.inventory.v1beta2.KesselInventoryService",
                        input=kessel_dot_inventory_dot_v1beta2_dot_check__for__update__request__pb2.CheckForUpdateRequest,
                        output=kessel_dot_inventory_dot_v1beta2_dot_check__for__update__response__pb2.CheckForUpdateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.check_for_update,
                ),
                "/kessel.inventory.v1beta2.KesselInventoryService/CheckForUpdateBulk": Endpoint.unary(
                    method=MethodInfo(
                        name="CheckForUpdateBulk",
                        service_name="kessel.inventory.v1beta2.KesselInventoryService",
                        input=kessel_dot_inventory_dot_v1beta2_dot_check__for__update__bulk__request__pb2.CheckForUpdateBulkRequest,
                        output=kessel_dot_inventory_dot_v1beta2_dot_check__for__update__bulk__response__pb2.CheckForUpdateBulkResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.check_for_update_bulk,
                ),
                "/kessel.inventory.v1beta2.KesselInventoryService/CheckBulk": Endpoint.unary(
                    method=MethodInfo(
                        name="CheckBulk",
                        service_name="kessel.inventory.v1beta2.KesselInventoryService",
                        input=kessel_dot_inventory_dot_v1beta2_dot_check__bulk__request__pb2.CheckBulkRequest,
                        output=kessel_dot_inventory_dot_v1beta2_dot_check__bulk__response__pb2.CheckBulkResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.check_bulk,
                ),
                "/kessel.inventory.v1beta2.KesselInventoryService/CheckSelfBulk": Endpoint.unary(
                    method=MethodInfo(
                        name="CheckSelfBulk",
                        service_name="kessel.inventory.v1beta2.KesselInventoryService",
                        input=kessel_dot_inventory_dot_v1beta2_dot_check__self__bulk__request__pb2.CheckSelfBulkRequest,
                        output=kessel_dot_inventory_dot_v1beta2_dot_check__self__bulk__response__pb2.CheckSelfBulkResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.check_self_bulk,
                ),
                "/kessel.inventory.v1beta2.KesselInventoryService/ReportResource": Endpoint.unary(
                    method=MethodInfo(
                        name="ReportResource",
                        service_name="kessel.inventory.v1beta2.KesselInventoryService",
                        input=kessel_dot_inventory_dot_v1beta2_dot_report__resource__request__pb2.ReportResourceRequest,
                        output=kessel_dot_inventory_dot_v1beta2_dot_report__resource__response__pb2.ReportResourceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.report_resource,
                ),
                "/kessel.inventory.v1beta2.KesselInventoryService/DeleteResource": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteResource",
                        service_name="kessel.inventory.v1beta2.KesselInventoryService",
                        input=kessel_dot_inventory_dot_v1beta2_dot_delete__resource__request__pb2.DeleteResourceRequest,
                        output=kessel_dot_inventory_dot_v1beta2_dot_delete__resource__response__pb2.DeleteResourceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_resource,
                ),
                "/kessel.inventory.v1beta2.KesselInventoryService/StreamedListObjects": Endpoint.server_stream(
                    method=MethodInfo(
                        name="StreamedListObjects",
                        service_name="kessel.inventory.v1beta2.KesselInventoryService",
                        input=kessel_dot_inventory_dot_v1beta2_dot_streamed__list__objects__request__pb2.StreamedListObjectsRequest,
                        output=kessel_dot_inventory_dot_v1beta2_dot_streamed__list__objects__response__pb2.StreamedListObjectsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.streamed_list_objects,
                ),
                "/kessel.inventory.v1beta2.KesselInventoryService/StreamedListSubjects": Endpoint.server_stream(
                    method=MethodInfo(
                        name="StreamedListSubjects",
                        service_name="kessel.inventory.v1beta2.KesselInventoryService",
                        input=kessel_dot_inventory_dot_v1beta2_dot_streamed__list__subjects__request__pb2.StreamedListSubjectsRequest,
                        output=kessel_dot_inventory_dot_v1beta2_dot_streamed__list__subjects__response__pb2.StreamedListSubjectsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.streamed_list_subjects,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kessel.inventory.v1beta2.KesselInventoryService"


class KesselInventoryServiceClient(ConnectClient):
    async def check(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__request__pb2.CheckRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kessel_dot_inventory_dot_v1beta2_dot_check__response__pb2.CheckResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Check",
                service_name="kessel.inventory.v1beta2.KesselInventoryService",
                input=kessel_dot_inventory_dot_v1beta2_dot_check__request__pb2.CheckRequest,
                output=kessel_dot_inventory_dot_v1beta2_dot_check__response__pb2.CheckResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def check_self(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__self__request__pb2.CheckSelfRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kessel_dot_inventory_dot_v1beta2_dot_check__self__response__pb2.CheckSelfResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CheckSelf",
                service_name="kessel.inventory.v1beta2.KesselInventoryService",
                input=kessel_dot_inventory_dot_v1beta2_dot_check__self__request__pb2.CheckSelfRequest,
                output=kessel_dot_inventory_dot_v1beta2_dot_check__self__response__pb2.CheckSelfResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def check_for_update(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__for__update__request__pb2.CheckForUpdateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> (
        kessel_dot_inventory_dot_v1beta2_dot_check__for__update__response__pb2.CheckForUpdateResponse
    ):
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CheckForUpdate",
                service_name="kessel.inventory.v1beta2.KesselInventoryService",
                input=kessel_dot_inventory_dot_v1beta2_dot_check__for__update__request__pb2.CheckForUpdateRequest,
                output=kessel_dot_inventory_dot_v1beta2_dot_check__for__update__response__pb2.CheckForUpdateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def check_for_update_bulk(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__for__update__bulk__request__pb2.CheckForUpdateBulkRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> (
        kessel_dot_inventory_dot_v1beta2_dot_check__for__update__bulk__response__pb2.CheckForUpdateBulkResponse
    ):
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CheckForUpdateBulk",
                service_name="kessel.inventory.v1beta2.KesselInventoryService",
                input=kessel_dot_inventory_dot_v1beta2_dot_check__for__update__bulk__request__pb2.CheckForUpdateBulkRequest,
                output=kessel_dot_inventory_dot_v1beta2_dot_check__for__update__bulk__response__pb2.CheckForUpdateBulkResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def check_bulk(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__bulk__request__pb2.CheckBulkRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kessel_dot_inventory_dot_v1beta2_dot_check__bulk__response__pb2.CheckBulkResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CheckBulk",
                service_name="kessel.inventory.v1beta2.KesselInventoryService",
                input=kessel_dot_inventory_dot_v1beta2_dot_check__bulk__request__pb2.CheckBulkRequest,
                output=kessel_dot_inventory_dot_v1beta2_dot_check__bulk__response__pb2.CheckBulkResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def check_self_bulk(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__self__bulk__request__pb2.CheckSelfBulkRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> (
        kessel_dot_inventory_dot_v1beta2_dot_check__self__bulk__response__pb2.CheckSelfBulkResponse
    ):
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CheckSelfBulk",
                service_name="kessel.inventory.v1beta2.KesselInventoryService",
                input=kessel_dot_inventory_dot_v1beta2_dot_check__self__bulk__request__pb2.CheckSelfBulkRequest,
                output=kessel_dot_inventory_dot_v1beta2_dot_check__self__bulk__response__pb2.CheckSelfBulkResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def report_resource(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_report__resource__request__pb2.ReportResourceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> (
        kessel_dot_inventory_dot_v1beta2_dot_report__resource__response__pb2.ReportResourceResponse
    ):
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ReportResource",
                service_name="kessel.inventory.v1beta2.KesselInventoryService",
                input=kessel_dot_inventory_dot_v1beta2_dot_report__resource__request__pb2.ReportResourceRequest,
                output=kessel_dot_inventory_dot_v1beta2_dot_report__resource__response__pb2.ReportResourceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_resource(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_delete__resource__request__pb2.DeleteResourceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> (
        kessel_dot_inventory_dot_v1beta2_dot_delete__resource__response__pb2.DeleteResourceResponse
    ):
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteResource",
                service_name="kessel.inventory.v1beta2.KesselInventoryService",
                input=kessel_dot_inventory_dot_v1beta2_dot_delete__resource__request__pb2.DeleteResourceRequest,
                output=kessel_dot_inventory_dot_v1beta2_dot_delete__resource__response__pb2.DeleteResourceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def streamed_list_objects(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_streamed__list__objects__request__pb2.StreamedListObjectsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[
        kessel_dot_inventory_dot_v1beta2_dot_streamed__list__objects__response__pb2.StreamedListObjectsResponse
    ]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="StreamedListObjects",
                service_name="kessel.inventory.v1beta2.KesselInventoryService",
                input=kessel_dot_inventory_dot_v1beta2_dot_streamed__list__objects__request__pb2.StreamedListObjectsRequest,
                output=kessel_dot_inventory_dot_v1beta2_dot_streamed__list__objects__response__pb2.StreamedListObjectsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def streamed_list_subjects(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_streamed__list__subjects__request__pb2.StreamedListSubjectsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[
        kessel_dot_inventory_dot_v1beta2_dot_streamed__list__subjects__response__pb2.StreamedListSubjectsResponse
    ]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="StreamedListSubjects",
                service_name="kessel.inventory.v1beta2.KesselInventoryService",
                input=kessel_dot_inventory_dot_v1beta2_dot_streamed__list__subjects__request__pb2.StreamedListSubjectsRequest,
                output=kessel_dot_inventory_dot_v1beta2_dot_streamed__list__subjects__response__pb2.StreamedListSubjectsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class KesselInventoryServiceSync(Protocol):
    def check(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__request__pb2.CheckRequest,
        ctx: RequestContext,
    ) -> kessel_dot_inventory_dot_v1beta2_dot_check__response__pb2.CheckResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def check_self(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__self__request__pb2.CheckSelfRequest,
        ctx: RequestContext,
    ) -> kessel_dot_inventory_dot_v1beta2_dot_check__self__response__pb2.CheckSelfResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def check_for_update(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__for__update__request__pb2.CheckForUpdateRequest,
        ctx: RequestContext,
    ) -> (
        kessel_dot_inventory_dot_v1beta2_dot_check__for__update__response__pb2.CheckForUpdateResponse
    ):
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def check_for_update_bulk(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__for__update__bulk__request__pb2.CheckForUpdateBulkRequest,
        ctx: RequestContext,
    ) -> (
        kessel_dot_inventory_dot_v1beta2_dot_check__for__update__bulk__response__pb2.CheckForUpdateBulkResponse
    ):
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def check_bulk(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__bulk__request__pb2.CheckBulkRequest,
        ctx: RequestContext,
    ) -> kessel_dot_inventory_dot_v1beta2_dot_check__bulk__response__pb2.CheckBulkResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def check_self_bulk(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__self__bulk__request__pb2.CheckSelfBulkRequest,
        ctx: RequestContext,
    ) -> (
        kessel_dot_inventory_dot_v1beta2_dot_check__self__bulk__response__pb2.CheckSelfBulkResponse
    ):
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def report_resource(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_report__resource__request__pb2.ReportResourceRequest,
        ctx: RequestContext,
    ) -> (
        kessel_dot_inventory_dot_v1beta2_dot_report__resource__response__pb2.ReportResourceResponse
    ):
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def delete_resource(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_delete__resource__request__pb2.DeleteResourceRequest,
        ctx: RequestContext,
    ) -> (
        kessel_dot_inventory_dot_v1beta2_dot_delete__resource__response__pb2.DeleteResourceResponse
    ):
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def streamed_list_objects(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_streamed__list__objects__request__pb2.StreamedListObjectsRequest,
        ctx: RequestContext,
    ) -> Iterator[
        kessel_dot_inventory_dot_v1beta2_dot_streamed__list__objects__response__pb2.StreamedListObjectsResponse
    ]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def streamed_list_subjects(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_streamed__list__subjects__request__pb2.StreamedListSubjectsRequest,
        ctx: RequestContext,
    ) -> Iterator[
        kessel_dot_inventory_dot_v1beta2_dot_streamed__list__subjects__response__pb2.StreamedListSubjectsResponse
    ]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class KesselInventoryServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: KesselInventoryServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/kessel.inventory.v1beta2.KesselInventoryService/Check": EndpointSync.unary(
                    method=MethodInfo(
                        name="Check",
                        service_name="kessel.inventory.v1beta2.KesselInventoryService",
                        input=kessel_dot_inventory_dot_v1beta2_dot_check__request__pb2.CheckRequest,
                        output=kessel_dot_inventory_dot_v1beta2_dot_check__response__pb2.CheckResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.check,
                ),
                "/kessel.inventory.v1beta2.KesselInventoryService/CheckSelf": EndpointSync.unary(
                    method=MethodInfo(
                        name="CheckSelf",
                        service_name="kessel.inventory.v1beta2.KesselInventoryService",
                        input=kessel_dot_inventory_dot_v1beta2_dot_check__self__request__pb2.CheckSelfRequest,
                        output=kessel_dot_inventory_dot_v1beta2_dot_check__self__response__pb2.CheckSelfResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.check_self,
                ),
                "/kessel.inventory.v1beta2.KesselInventoryService/CheckForUpdate": EndpointSync.unary(
                    method=MethodInfo(
                        name="CheckForUpdate",
                        service_name="kessel.inventory.v1beta2.KesselInventoryService",
                        input=kessel_dot_inventory_dot_v1beta2_dot_check__for__update__request__pb2.CheckForUpdateRequest,
                        output=kessel_dot_inventory_dot_v1beta2_dot_check__for__update__response__pb2.CheckForUpdateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.check_for_update,
                ),
                "/kessel.inventory.v1beta2.KesselInventoryService/CheckForUpdateBulk": EndpointSync.unary(
                    method=MethodInfo(
                        name="CheckForUpdateBulk",
                        service_name="kessel.inventory.v1beta2.KesselInventoryService",
                        input=kessel_dot_inventory_dot_v1beta2_dot_check__for__update__bulk__request__pb2.CheckForUpdateBulkRequest,
                        output=kessel_dot_inventory_dot_v1beta2_dot_check__for__update__bulk__response__pb2.CheckForUpdateBulkResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.check_for_update_bulk,
                ),
                "/kessel.inventory.v1beta2.KesselInventoryService/CheckBulk": EndpointSync.unary(
                    method=MethodInfo(
                        name="CheckBulk",
                        service_name="kessel.inventory.v1beta2.KesselInventoryService",
                        input=kessel_dot_inventory_dot_v1beta2_dot_check__bulk__request__pb2.CheckBulkRequest,
                        output=kessel_dot_inventory_dot_v1beta2_dot_check__bulk__response__pb2.CheckBulkResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.check_bulk,
                ),
                "/kessel.inventory.v1beta2.KesselInventoryService/CheckSelfBulk": EndpointSync.unary(
                    method=MethodInfo(
                        name="CheckSelfBulk",
                        service_name="kessel.inventory.v1beta2.KesselInventoryService",
                        input=kessel_dot_inventory_dot_v1beta2_dot_check__self__bulk__request__pb2.CheckSelfBulkRequest,
                        output=kessel_dot_inventory_dot_v1beta2_dot_check__self__bulk__response__pb2.CheckSelfBulkResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.check_self_bulk,
                ),
                "/kessel.inventory.v1beta2.KesselInventoryService/ReportResource": EndpointSync.unary(
                    method=MethodInfo(
                        name="ReportResource",
                        service_name="kessel.inventory.v1beta2.KesselInventoryService",
                        input=kessel_dot_inventory_dot_v1beta2_dot_report__resource__request__pb2.ReportResourceRequest,
                        output=kessel_dot_inventory_dot_v1beta2_dot_report__resource__response__pb2.ReportResourceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.report_resource,
                ),
                "/kessel.inventory.v1beta2.KesselInventoryService/DeleteResource": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteResource",
                        service_name="kessel.inventory.v1beta2.KesselInventoryService",
                        input=kessel_dot_inventory_dot_v1beta2_dot_delete__resource__request__pb2.DeleteResourceRequest,
                        output=kessel_dot_inventory_dot_v1beta2_dot_delete__resource__response__pb2.DeleteResourceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_resource,
                ),
                "/kessel.inventory.v1beta2.KesselInventoryService/StreamedListObjects": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="StreamedListObjects",
                        service_name="kessel.inventory.v1beta2.KesselInventoryService",
                        input=kessel_dot_inventory_dot_v1beta2_dot_streamed__list__objects__request__pb2.StreamedListObjectsRequest,
                        output=kessel_dot_inventory_dot_v1beta2_dot_streamed__list__objects__response__pb2.StreamedListObjectsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.streamed_list_objects,
                ),
                "/kessel.inventory.v1beta2.KesselInventoryService/StreamedListSubjects": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="StreamedListSubjects",
                        service_name="kessel.inventory.v1beta2.KesselInventoryService",
                        input=kessel_dot_inventory_dot_v1beta2_dot_streamed__list__subjects__request__pb2.StreamedListSubjectsRequest,
                        output=kessel_dot_inventory_dot_v1beta2_dot_streamed__list__subjects__response__pb2.StreamedListSubjectsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.streamed_list_subjects,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kessel.inventory.v1beta2.KesselInventoryService"


class KesselInventoryServiceClientSync(ConnectClientSync):
    def check(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__request__pb2.CheckRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kessel_dot_inventory_dot_v1beta2_dot_check__response__pb2.CheckResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Check",
                service_name="kessel.inventory.v1beta2.KesselInventoryService",
                input=kessel_dot_inventory_dot_v1beta2_dot_check__request__pb2.CheckRequest,
                output=kessel_dot_inventory_dot_v1beta2_dot_check__response__pb2.CheckResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def check_self(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__self__request__pb2.CheckSelfRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kessel_dot_inventory_dot_v1beta2_dot_check__self__response__pb2.CheckSelfResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CheckSelf",
                service_name="kessel.inventory.v1beta2.KesselInventoryService",
                input=kessel_dot_inventory_dot_v1beta2_dot_check__self__request__pb2.CheckSelfRequest,
                output=kessel_dot_inventory_dot_v1beta2_dot_check__self__response__pb2.CheckSelfResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def check_for_update(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__for__update__request__pb2.CheckForUpdateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> (
        kessel_dot_inventory_dot_v1beta2_dot_check__for__update__response__pb2.CheckForUpdateResponse
    ):
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CheckForUpdate",
                service_name="kessel.inventory.v1beta2.KesselInventoryService",
                input=kessel_dot_inventory_dot_v1beta2_dot_check__for__update__request__pb2.CheckForUpdateRequest,
                output=kessel_dot_inventory_dot_v1beta2_dot_check__for__update__response__pb2.CheckForUpdateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def check_for_update_bulk(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__for__update__bulk__request__pb2.CheckForUpdateBulkRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> (
        kessel_dot_inventory_dot_v1beta2_dot_check__for__update__bulk__response__pb2.CheckForUpdateBulkResponse
    ):
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CheckForUpdateBulk",
                service_name="kessel.inventory.v1beta2.KesselInventoryService",
                input=kessel_dot_inventory_dot_v1beta2_dot_check__for__update__bulk__request__pb2.CheckForUpdateBulkRequest,
                output=kessel_dot_inventory_dot_v1beta2_dot_check__for__update__bulk__response__pb2.CheckForUpdateBulkResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def check_bulk(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__bulk__request__pb2.CheckBulkRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kessel_dot_inventory_dot_v1beta2_dot_check__bulk__response__pb2.CheckBulkResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CheckBulk",
                service_name="kessel.inventory.v1beta2.KesselInventoryService",
                input=kessel_dot_inventory_dot_v1beta2_dot_check__bulk__request__pb2.CheckBulkRequest,
                output=kessel_dot_inventory_dot_v1beta2_dot_check__bulk__response__pb2.CheckBulkResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def check_self_bulk(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_check__self__bulk__request__pb2.CheckSelfBulkRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> (
        kessel_dot_inventory_dot_v1beta2_dot_check__self__bulk__response__pb2.CheckSelfBulkResponse
    ):
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CheckSelfBulk",
                service_name="kessel.inventory.v1beta2.KesselInventoryService",
                input=kessel_dot_inventory_dot_v1beta2_dot_check__self__bulk__request__pb2.CheckSelfBulkRequest,
                output=kessel_dot_inventory_dot_v1beta2_dot_check__self__bulk__response__pb2.CheckSelfBulkResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def report_resource(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_report__resource__request__pb2.ReportResourceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> (
        kessel_dot_inventory_dot_v1beta2_dot_report__resource__response__pb2.ReportResourceResponse
    ):
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ReportResource",
                service_name="kessel.inventory.v1beta2.KesselInventoryService",
                input=kessel_dot_inventory_dot_v1beta2_dot_report__resource__request__pb2.ReportResourceRequest,
                output=kessel_dot_inventory_dot_v1beta2_dot_report__resource__response__pb2.ReportResourceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_resource(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_delete__resource__request__pb2.DeleteResourceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> (
        kessel_dot_inventory_dot_v1beta2_dot_delete__resource__response__pb2.DeleteResourceResponse
    ):
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteResource",
                service_name="kessel.inventory.v1beta2.KesselInventoryService",
                input=kessel_dot_inventory_dot_v1beta2_dot_delete__resource__request__pb2.DeleteResourceRequest,
                output=kessel_dot_inventory_dot_v1beta2_dot_delete__resource__response__pb2.DeleteResourceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def streamed_list_objects(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_streamed__list__objects__request__pb2.StreamedListObjectsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[
        kessel_dot_inventory_dot_v1beta2_dot_streamed__list__objects__response__pb2.StreamedListObjectsResponse
    ]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="StreamedListObjects",
                service_name="kessel.inventory.v1beta2.KesselInventoryService",
                input=kessel_dot_inventory_dot_v1beta2_dot_streamed__list__objects__request__pb2.StreamedListObjectsRequest,
                output=kessel_dot_inventory_dot_v1beta2_dot_streamed__list__objects__response__pb2.StreamedListObjectsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def streamed_list_subjects(
        self,
        request: kessel_dot_inventory_dot_v1beta2_dot_streamed__list__subjects__request__pb2.StreamedListSubjectsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[
        kessel_dot_inventory_dot_v1beta2_dot_streamed__list__subjects__response__pb2.StreamedListSubjectsResponse
    ]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="StreamedListSubjects",
                service_name="kessel.inventory.v1beta2.KesselInventoryService",
                input=kessel_dot_inventory_dot_v1beta2_dot_streamed__list__subjects__request__pb2.StreamedListSubjectsRequest,
                output=kessel_dot_inventory_dot_v1beta2_dot_streamed__list__subjects__response__pb2.StreamedListSubjectsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
