# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kessel/inventory/v1beta2/relationship.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kessel/inventory/v1beta2/relationship.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from kessel.inventory.v1beta2 import relation_object_reference_pb2 as kessel_dot_inventory_dot_v1beta2_dot_relation__object__reference__pb2
from kessel.inventory.v1beta2 import relation_subject_reference_pb2 as kessel_dot_inventory_dot_v1beta2_dot_relation__subject__reference__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+kessel/inventory/v1beta2/relationship.proto\x12\x18kessel.inventory.v1beta2\x1a\x1b\x62uf/validate/validate.proto\x1a\x38kessel/inventory/v1beta2/relation_object_reference.proto\x1a\x39kessel/inventory/v1beta2/relation_subject_reference.proto\"\xe0\x01\n\x0cRelationship\x12U\n\x08resource\x18\x01 \x01(\x0b\x32\x31.kessel.inventory.v1beta2.RelationObjectReferenceB\x06\xbaH\x03\xc8\x01\x01R\x08resource\x12#\n\x08relation\x18\x02 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x08relation\x12T\n\x07subject\x18\x03 \x01(\x0b\x32\x32.kessel.inventory.v1beta2.RelationSubjectReferenceB\x06\xbaH\x03\xc8\x01\x01R\x07subjectBr\n(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kessel.inventory.v1beta2.relationship_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(org.project_kessel.api.inventory.v1beta2P\001ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2'
  _globals['_RELATIONSHIP'].fields_by_name['resource']._loaded_options = None
  _globals['_RELATIONSHIP'].fields_by_name['resource']._serialized_options = b'\272H\003\310\001\001'
  _globals['_RELATIONSHIP'].fields_by_name['relation']._loaded_options = None
  _globals['_RELATIONSHIP'].fields_by_name['relation']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_RELATIONSHIP'].fields_by_name['subject']._loaded_options = None
  _globals['_RELATIONSHIP'].fields_by_name['subject']._serialized_options = b'\272H\003\310\001\001'
  _globals['_RELATIONSHIP']._serialized_start=220
  _globals['_RELATIONSHIP']._serialized_end=444
# @@protoc_insertion_point(module_scope)
