# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kessel/inventory/v1beta2/streamed_list_subjects_request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kessel/inventory/v1beta2/streamed_list_subjects_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from kessel.inventory.v1beta2 import resource_reference_pb2 as kessel_dot_inventory_dot_v1beta2_dot_resource__reference__pb2
from kessel.inventory.v1beta2 import representation_type_pb2 as kessel_dot_inventory_dot_v1beta2_dot_representation__type__pb2
from kessel.inventory.v1beta2 import request_pagination_pb2 as kessel_dot_inventory_dot_v1beta2_dot_request__pagination__pb2
from kessel.inventory.v1beta2 import consistency_pb2 as kessel_dot_inventory_dot_v1beta2_dot_consistency__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=kessel/inventory/v1beta2/streamed_list_subjects_request.proto\x12\x18kessel.inventory.v1beta2\x1a\x1b\x62uf/validate/validate.proto\x1a\x31kessel/inventory/v1beta2/resource_reference.proto\x1a\x32kessel/inventory/v1beta2/representation_type.proto\x1a\x31kessel/inventory/v1beta2/request_pagination.proto\x1a*kessel/inventory/v1beta2/consistency.proto\"\xf0\x03\n\x1bStreamedListSubjectsRequest\x12O\n\x08resource\x18\x01 \x01(\x0b\x32+.kessel.inventory.v1beta2.ResourceReferenceB\x06\xbaH\x03\xc8\x01\x01R\x08resource\x12#\n\x08relation\x18\x02 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x08relation\x12W\n\x0csubject_type\x18\x03 \x01(\x0b\x32,.kessel.inventory.v1beta2.RepresentationTypeB\x06\xbaH\x03\xc8\x01\x01R\x0bsubjectType\x12.\n\x10subject_relation\x18\x04 \x01(\tH\x00R\x0fsubjectRelation\x88\x01\x01\x12P\n\npagination\x18\x05 \x01(\x0b\x32+.kessel.inventory.v1beta2.RequestPaginationH\x01R\npagination\x88\x01\x01\x12L\n\x0b\x63onsistency\x18\x06 \x01(\x0b\x32%.kessel.inventory.v1beta2.ConsistencyH\x02R\x0b\x63onsistency\x88\x01\x01\x42\x13\n\x11_subject_relationB\r\n\x0b_paginationB\x0e\n\x0c_consistencyBr\n(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kessel.inventory.v1beta2.streamed_list_subjects_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(org.project_kessel.api.inventory.v1beta2P\001ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2'
  _globals['_STREAMEDLISTSUBJECTSREQUEST'].fields_by_name['resource']._loaded_options = None
  _globals['_STREAMEDLISTSUBJECTSREQUEST'].fields_by_name['resource']._serialized_options = b'\272H\003\310\001\001'
  _globals['_STREAMEDLISTSUBJECTSREQUEST'].fields_by_name['relation']._loaded_options = None
  _globals['_STREAMEDLISTSUBJECTSREQUEST'].fields_by_name['relation']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_STREAMEDLISTSUBJECTSREQUEST'].fields_by_name['subject_type']._loaded_options = None
  _globals['_STREAMEDLISTSUBJECTSREQUEST'].fields_by_name['subject_type']._serialized_options = b'\272H\003\310\001\001'
  _globals['_STREAMEDLISTSUBJECTSREQUEST']._serialized_start=319
  _globals['_STREAMEDLISTSUBJECTSREQUEST']._serialized_end=815
# @@protoc_insertion_point(module_scope)
