# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kessel.inventory.v1beta2 import acquire_lock_request_pb2 as kessel_dot_inventory_dot_v1beta2_dot_acquire__lock__request__pb2
from kessel.inventory.v1beta2 import acquire_lock_response_pb2 as kessel_dot_inventory_dot_v1beta2_dot_acquire__lock__response__pb2
from kessel.inventory.v1beta2 import create_tuples_request_pb2 as kessel_dot_inventory_dot_v1beta2_dot_create__tuples__request__pb2
from kessel.inventory.v1beta2 import create_tuples_response_pb2 as kessel_dot_inventory_dot_v1beta2_dot_create__tuples__response__pb2
from kessel.inventory.v1beta2 import delete_tuples_request_pb2 as kessel_dot_inventory_dot_v1beta2_dot_delete__tuples__request__pb2
from kessel.inventory.v1beta2 import delete_tuples_response_pb2 as kessel_dot_inventory_dot_v1beta2_dot_delete__tuples__response__pb2
from kessel.inventory.v1beta2 import read_tuples_request_pb2 as kessel_dot_inventory_dot_v1beta2_dot_read__tuples__request__pb2
from kessel.inventory.v1beta2 import read_tuples_response_pb2 as kessel_dot_inventory_dot_v1beta2_dot_read__tuples__response__pb2


class KesselTupleServiceStub(object):
    """DEPRECATED: KesselTupleService provides legacy tuple-layer operations.
    This service exists only for RBAC backward compatibility and will be removed.
    All endpoints are marked deprecated. Do not add new consumers.
    Use KesselInventoryService's ReportResource for new integrations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTuples = channel.unary_unary(
                '/kessel.inventory.v1beta2.KesselTupleService/CreateTuples',
                request_serializer=kessel_dot_inventory_dot_v1beta2_dot_create__tuples__request__pb2.CreateTuplesRequest.SerializeToString,
                response_deserializer=kessel_dot_inventory_dot_v1beta2_dot_create__tuples__response__pb2.CreateTuplesResponse.FromString,
                _registered_method=True)
        self.DeleteTuples = channel.unary_unary(
                '/kessel.inventory.v1beta2.KesselTupleService/DeleteTuples',
                request_serializer=kessel_dot_inventory_dot_v1beta2_dot_delete__tuples__request__pb2.DeleteTuplesRequest.SerializeToString,
                response_deserializer=kessel_dot_inventory_dot_v1beta2_dot_delete__tuples__response__pb2.DeleteTuplesResponse.FromString,
                _registered_method=True)
        self.ReadTuples = channel.unary_stream(
                '/kessel.inventory.v1beta2.KesselTupleService/ReadTuples',
                request_serializer=kessel_dot_inventory_dot_v1beta2_dot_read__tuples__request__pb2.ReadTuplesRequest.SerializeToString,
                response_deserializer=kessel_dot_inventory_dot_v1beta2_dot_read__tuples__response__pb2.ReadTuplesResponse.FromString,
                _registered_method=True)
        self.AcquireLock = channel.unary_unary(
                '/kessel.inventory.v1beta2.KesselTupleService/AcquireLock',
                request_serializer=kessel_dot_inventory_dot_v1beta2_dot_acquire__lock__request__pb2.AcquireLockRequest.SerializeToString,
                response_deserializer=kessel_dot_inventory_dot_v1beta2_dot_acquire__lock__response__pb2.AcquireLockResponse.FromString,
                _registered_method=True)


class KesselTupleServiceServicer(object):
    """DEPRECATED: KesselTupleService provides legacy tuple-layer operations.
    This service exists only for RBAC backward compatibility and will be removed.
    All endpoints are marked deprecated. Do not add new consumers.
    Use KesselInventoryService's ReportResource for new integrations.
    """

    def CreateTuples(self, request, context):
        """DEPRECATED: CreateTuples creates relationship tuples.
        This endpoint exists only for RBAC backward compatibility.
        Use ReportResource instead for new code.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTuples(self, request, context):
        """DEPRECATED: DeleteTuples deletes relationship tuples.
        This endpoint exists only for RBAC backward compatibility.
        Use DeleteResource instead for new code.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadTuples(self, request, context):
        """DEPRECATED: ReadTuples reads relationship tuples.
        This endpoint exists only for RBAC backward compatibility.
        Use StreamedListObjects/StreamedListSubjects instead for new code.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcquireLock(self, request, context):
        """DEPRECATED: AcquireLock acquires a distributed lock.
        This endpoint exists only for RBAC backward compatibility.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KesselTupleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTuples': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTuples,
                    request_deserializer=kessel_dot_inventory_dot_v1beta2_dot_create__tuples__request__pb2.CreateTuplesRequest.FromString,
                    response_serializer=kessel_dot_inventory_dot_v1beta2_dot_create__tuples__response__pb2.CreateTuplesResponse.SerializeToString,
            ),
            'DeleteTuples': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTuples,
                    request_deserializer=kessel_dot_inventory_dot_v1beta2_dot_delete__tuples__request__pb2.DeleteTuplesRequest.FromString,
                    response_serializer=kessel_dot_inventory_dot_v1beta2_dot_delete__tuples__response__pb2.DeleteTuplesResponse.SerializeToString,
            ),
            'ReadTuples': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadTuples,
                    request_deserializer=kessel_dot_inventory_dot_v1beta2_dot_read__tuples__request__pb2.ReadTuplesRequest.FromString,
                    response_serializer=kessel_dot_inventory_dot_v1beta2_dot_read__tuples__response__pb2.ReadTuplesResponse.SerializeToString,
            ),
            'AcquireLock': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireLock,
                    request_deserializer=kessel_dot_inventory_dot_v1beta2_dot_acquire__lock__request__pb2.AcquireLockRequest.FromString,
                    response_serializer=kessel_dot_inventory_dot_v1beta2_dot_acquire__lock__response__pb2.AcquireLockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kessel.inventory.v1beta2.KesselTupleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kessel.inventory.v1beta2.KesselTupleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KesselTupleService(object):
    """DEPRECATED: KesselTupleService provides legacy tuple-layer operations.
    This service exists only for RBAC backward compatibility and will be removed.
    All endpoints are marked deprecated. Do not add new consumers.
    Use KesselInventoryService's ReportResource for new integrations.
    """

    @staticmethod
    def CreateTuples(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kessel.inventory.v1beta2.KesselTupleService/CreateTuples',
            kessel_dot_inventory_dot_v1beta2_dot_create__tuples__request__pb2.CreateTuplesRequest.SerializeToString,
            kessel_dot_inventory_dot_v1beta2_dot_create__tuples__response__pb2.CreateTuplesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTuples(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kessel.inventory.v1beta2.KesselTupleService/DeleteTuples',
            kessel_dot_inventory_dot_v1beta2_dot_delete__tuples__request__pb2.DeleteTuplesRequest.SerializeToString,
            kessel_dot_inventory_dot_v1beta2_dot_delete__tuples__response__pb2.DeleteTuplesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadTuples(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kessel.inventory.v1beta2.KesselTupleService/ReadTuples',
            kessel_dot_inventory_dot_v1beta2_dot_read__tuples__request__pb2.ReadTuplesRequest.SerializeToString,
            kessel_dot_inventory_dot_v1beta2_dot_read__tuples__response__pb2.ReadTuplesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcquireLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kessel.inventory.v1beta2.KesselTupleService/AcquireLock',
            kessel_dot_inventory_dot_v1beta2_dot_acquire__lock__request__pb2.AcquireLockRequest.SerializeToString,
            kessel_dot_inventory_dot_v1beta2_dot_acquire__lock__response__pb2.AcquireLockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
