# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kessel/inventory/v1beta2/tuple_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kessel/inventory/v1beta2/tuple_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kessel.inventory.v1beta2 import create_tuples_request_pb2 as kessel_dot_inventory_dot_v1beta2_dot_create__tuples__request__pb2
from kessel.inventory.v1beta2 import create_tuples_response_pb2 as kessel_dot_inventory_dot_v1beta2_dot_create__tuples__response__pb2
from kessel.inventory.v1beta2 import read_tuples_request_pb2 as kessel_dot_inventory_dot_v1beta2_dot_read__tuples__request__pb2
from kessel.inventory.v1beta2 import read_tuples_response_pb2 as kessel_dot_inventory_dot_v1beta2_dot_read__tuples__response__pb2
from kessel.inventory.v1beta2 import delete_tuples_request_pb2 as kessel_dot_inventory_dot_v1beta2_dot_delete__tuples__request__pb2
from kessel.inventory.v1beta2 import delete_tuples_response_pb2 as kessel_dot_inventory_dot_v1beta2_dot_delete__tuples__response__pb2
from kessel.inventory.v1beta2 import acquire_lock_request_pb2 as kessel_dot_inventory_dot_v1beta2_dot_acquire__lock__request__pb2
from kessel.inventory.v1beta2 import acquire_lock_response_pb2 as kessel_dot_inventory_dot_v1beta2_dot_acquire__lock__response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,kessel/inventory/v1beta2/tuple_service.proto\x12\x18kessel.inventory.v1beta2\x1a\x34kessel/inventory/v1beta2/create_tuples_request.proto\x1a\x35kessel/inventory/v1beta2/create_tuples_response.proto\x1a\x32kessel/inventory/v1beta2/read_tuples_request.proto\x1a\x33kessel/inventory/v1beta2/read_tuples_response.proto\x1a\x34kessel/inventory/v1beta2/delete_tuples_request.proto\x1a\x35kessel/inventory/v1beta2/delete_tuples_response.proto\x1a\x33kessel/inventory/v1beta2/acquire_lock_request.proto\x1a\x34kessel/inventory/v1beta2/acquire_lock_response.proto2\xdd\x03\n\x12KesselTupleService\x12r\n\x0c\x43reateTuples\x12-.kessel.inventory.v1beta2.CreateTuplesRequest\x1a..kessel.inventory.v1beta2.CreateTuplesResponse\"\x03\x88\x02\x01\x12r\n\x0c\x44\x65leteTuples\x12-.kessel.inventory.v1beta2.DeleteTuplesRequest\x1a..kessel.inventory.v1beta2.DeleteTuplesResponse\"\x03\x88\x02\x01\x12n\n\nReadTuples\x12+.kessel.inventory.v1beta2.ReadTuplesRequest\x1a,.kessel.inventory.v1beta2.ReadTuplesResponse\"\x03\x88\x02\x01\x30\x01\x12o\n\x0b\x41\x63quireLock\x12,.kessel.inventory.v1beta2.AcquireLockRequest\x1a-.kessel.inventory.v1beta2.AcquireLockResponse\"\x03\x88\x02\x01\x42r\n(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kessel.inventory.v1beta2.tuple_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(org.project_kessel.api.inventory.v1beta2P\001ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2'
  _globals['_KESSELTUPLESERVICE'].methods_by_name['CreateTuples']._loaded_options = None
  _globals['_KESSELTUPLESERVICE'].methods_by_name['CreateTuples']._serialized_options = b'\210\002\001'
  _globals['_KESSELTUPLESERVICE'].methods_by_name['DeleteTuples']._loaded_options = None
  _globals['_KESSELTUPLESERVICE'].methods_by_name['DeleteTuples']._serialized_options = b'\210\002\001'
  _globals['_KESSELTUPLESERVICE'].methods_by_name['ReadTuples']._loaded_options = None
  _globals['_KESSELTUPLESERVICE'].methods_by_name['ReadTuples']._serialized_options = b'\210\002\001'
  _globals['_KESSELTUPLESERVICE'].methods_by_name['AcquireLock']._loaded_options = None
  _globals['_KESSELTUPLESERVICE'].methods_by_name['AcquireLock']._serialized_options = b'\210\002\001'
  _globals['_KESSELTUPLESERVICE']._serialized_start=505
  _globals['_KESSELTUPLESERVICE']._serialized_end=982
# @@protoc_insertion_point(module_scope)
